### ISSUE TITLE
Windows 上配置 FASTAPI_RELOAD=true 后，数据库迁移失败

### ISSUE THREAD

**Issue by he0119** [felinae98/nonebot-bison#116]
Windows 上配置 FASTAPI_RELOAD=true 后，数据库迁移失败。 错误日志如下：

```log
10-10 19:50:28 [ERROR] uvicorn | Traceback (most recent call last):
  File ".\.venv\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File ".\.venv\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File ".\.venv\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File ".\.venv\lib\site-packages\nonebot_bison\bootstrap.py", line 15, in bootstrap
    await upgrade_db()
  File ".\.venv\lib\site-packages\nonebot_bison\config\db.py", line 109, in upgrade_db
    await data_migrate()
  File ".\.venv\lib\site-packages\nonebot_bison\config\db.py", line 78, in data_migrate
    drop()
  File ".\.venv\lib\site-packages\nonebot_bison\config\config_legacy.py", line 46, in drop
    os.rename(old_path, new_path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: './data/bison\\bison.json' -> './data/bison\\bison-legacy.json'
```

**Comment by felinae98** [comment]
如果遇到这个问题，并且再次启动机器人失败，请手动把 bison.json 重命名为 bison-legacy.json

**Comment by felinae98** [comment]
fixed in #120
