### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by forchannot** [felinae98/nonebot-bison#144]
11-21 18:00:10 [ERROR] apscheduler | Job "Scheduler.exec_fetch (trigger: interval[0:00:03], next run at: 2022-11-21 18:00:12 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\fwq\LittlePaimon\bot.py", line 40, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
    │       └ <function run at 0x000002EA01ED6050>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\littlepaimon-EfRlD-3A-py3.10\...
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': '__mp_main__:app', 'access_log': False}
    │                 └ ()
    └ <function get_driver at 0x000002EA7F5A1F30>
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x000002EA030F9EA0>
    └ <module 'uvicorn' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\littlepaimon-EfRlD-3A-py3.10\...
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
    │      └ <function Server.run at 0x000002EA030FA050>
    └ <uvicorn.server.Server object at 0x000002EA1D4C2710>
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000002EA030FA0E0>
           │       │   └ <uvicorn.server.Server object at 0x000002EA1D4C2710>
           │       └ <function run at 0x000002EA7F9C9120>
           └ <module 'asyncio' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\__init__.py'>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x000002EA1D4A99A0>
           │    └ <function BaseEventLoop.run_until_complete at 0x000002EA7FACD7E0>
           └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002EA7FB82200>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002EA7FACF250>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002EA7FA71EA0>
    └ <Handle <TaskStepMethWrapper object at 0x000002EA1DAE8C40>()>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000002EA1DAE8C40>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000002EA1DAE8C40>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000002EA1DAE8C40>()>
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=61273b31a6714a898af867ced56d6dec name=Scheduler.exec_fetch)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=61273b31a6714a898af867ced56d6dec name=Scheduler.exec_fetch)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=61273b31a6714a898af867ced56d6dec name=Scheduler.exec_fetch)>
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_bison\scheduler\scheduler.py", line 107, in exec_fetch
    await send_post.generate_messages(),
          │         └ <function AbstractPost.generate_messages at 0x000002EA0C2900D0>
          └ Post(target_type='weibo', text='云图计划#云图计划#\n全新人形渡宾即将实装！\n\nDetectiveD，环球万事服务出品的侦察类专业人形\n2053年，巴黎蒙马特侦探事务所购入DetectiveD系列初号人形渡宾。...
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_bison\post\abstract_post.py", line 42, in generate_messages
    msg_segments = await self.generate_pic_messages()
                         │    └ <function _Post.generate_pic_messages at 0x000002EA0C2905E0>
                         └ Post(target_type='weibo', text='云图计划#云图计划#\n全新人形渡宾即将实装！\n\nDetectiveD，环球万事服务出品的侦察类专业人形\n2053年，巴黎蒙马特侦探事务所购入DetectiveD系列初号人形渡宾。...
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_bison\post\post.py", line 128, in generate_pic_messages
    await self._pic_merge()
          │    └ <function _Post._pic_merge at 0x000002EA0C2904C0>
          └ Post(target_type='weibo', text='云图计划#云图计划#\n全新人形渡宾即将实装！\n\nDetectiveD，环球万事服务出品的侦察类专业人形\n2053年，巴黎蒙马特侦探事务所购入DetectiveD系列初号人形渡宾。...
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_bison\post\post.py", line 42, in _pic_merge
    first_image = await self._pic_url_to_image(self.pics[0])
                        │    │                 │    └ ['https://wx3.sinaimg.cn/large/007YAn52gy1h8cuulu933j31hc0u0h23.jpg', 'https://wx4.sinaimg.cn/large/007YAn52gy1h8cuuo1ujcj30u...
                        │    │                 └ Post(target_type='weibo', text='云图计划#云图计划#\n全新人形渡宾即将实装！\n\nDetectiveD，环球万事服务出品的侦察类专业人形\n2053年，巴黎蒙马特侦探事务所购入DetectiveD系列初号人形渡宾。...
                        │    └ <function _Post._pic_url_to_image at 0x000002EA0C223A30>
                        └ Post(target_type='weibo', text='云图计划#云图计划#\n全新人形渡宾即将实装！\n\nDetectiveD，环球万事服务出品的侦察类专业人形\n2053年，巴黎蒙马特侦探事务所购入DetectiveD系列初号人形渡宾。...
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\nonebot_bison\post\post.py", line 34, in _pic_url_to_image
    return Image.open(pic_buffer)
           │     │    └ <_io.BytesIO object at 0x000002EA1DE36C50>
           │     └ <function open at 0x000002EA05CF52D0>
           └ <module 'PIL.Image' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\littlepaimon-EfRlD-3A-py3.1...
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepaimon-EfRlD-3A-py3.10\lib\site-packages\PIL\Image.py", line 3186, in open
    raise UnidentifiedImageError(
          └ <class 'PIL.UnidentifiedImageError'>
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002EA1DE36C50>

**Comment by forchannot** [comment]
今天漏了挺多订阅的，但是日志找不到了，不清楚是不是全是这个报错

**Comment by forchannot** [comment]
emmmm，是因为改成了渲染成图片发送的原因嘛。以前如果图片发不出来文字也可以发过来，现在渲染成图片偶尔就啥也发不出来这样了。今天至少漏了四五个订阅，之前基本没漏过

**Comment by he0119** [comment]
不是，感觉是向微博服务器请求图片的时候，返回了错误的数据。

**Comment by felinae98** [comment]
今天或者明天
