### ISSUE TITLE
更新到最新版后报错：Multiple classes found for path "User" in the registry of this declarative base. Please use a fully module-qualified path.

### ISSUE THREAD

**Issue by yuanbuhuo** [felinae98/nonebot-bison#195]
```
02-14 09:23:14 [WARNING] apscheduler | Run time of job "Scheduler.exec_fetch (trigger: interval[0:00:03], next run at: 2023-02-14 09:23:15 CST)" was missed by 0

:00:01.519486
02-14 09:23:14 [ERROR] apscheduler | Job "Scheduler.exec_fetch (trigger: interval[0:00:10], next run at: 2023-02-14 09:23:23 CST)" raised an exception
Traceback (most recent call last):
  File "C:\NoneBot2\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\NoneBot2\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\NoneBot2\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\NoneBot2\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\NoneBot2\.venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\nonebot_bison\scheduler\scheduler.py", line 82, in exec_fetch
    if not (schedulable := await self.get_next_schedulable()):
  File "C:\NoneBot2\.venv\lib\site-packages\nonebot_bison\scheduler\scheduler.py", line 60, in get_next_schedulable
    cur_weight = await config.get_current_weight_val(self.platform_name_list)
  File "C:\NoneBot2\.venv\lib\site-packages\nonebot_bison\config\db_config.py", line 225, in get_current_weight_val
    await sess.scalars(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 272, in scalars
    result = await self.execute(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 215, in execute
    result = await greenlet_spawn(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 128, in greenlet_spawn
    result = context.switch(value)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlmodel\orm\session.py", line 101, in execute
    return super().execute(  # type: ignore
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1564, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 531, in _compile_w_cache
    compiled_sql = self._compiler(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 566, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 790, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 463, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 498, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 3301, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 699, in create_for_statement
    _QueryEntity.to_compile_state(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 2451, in to_compile_state
    _MapperEntity(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 2563, in __init__
    self._with_polymorphic_mappers = ext_info.with_polymorphic_mappers
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 2165, in _with_polymorphic_mappers
    self._check_configure()
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1924, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3483, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3522, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1941, in _post_configure_properties
    prop.init()
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 231, in init
    self.do_init()
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2150, in do_init
    self._generate_backref()
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2483, in _generate_backref
    mapper._configure_property(backref_key, relationship)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1833, in _configure_property
    prop.init()
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\interfaces.py", line 231, in init
    self.do_init()
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2145, in do_init
    self._process_dependent_arguments()
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 2185, in _process_dependent_arguments
    self._clsregistry_resolve_arg(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 408, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\util\_collections.py", line 746, in __missing__
    self[key] = val = self.creator(key)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 352, in _access_cls
    return _determine_container(key, decl_class_registry[key])
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 313, in _determine_container
    value = value.attempt_get([], key)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 144, in attempt_get
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Multiple classes found for path "User" in the registry of this declarative base. Please use a fully module-qualified path.
02-14 09:23:15 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\NoneBot2\.venv\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\NoneBot2\.venv\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\NoneBot2\.venv\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\NoneBot2\GenshinUID-nonebot2\GenshinUID\genshinuid_webconsole\__init__.py", line 44, in start_check
    await run_webconsole()
  File "C:\NoneBot2\GenshinUID-nonebot2\GenshinUID\genshinuid_webconsole\__init__.py", line 31, in run_webconsole
    await auth.create_role_user()
  File "C:\NoneBot2\.venv\lib\site-packages\fastapi_user_auth\auth\auth.py", line 228, in create_role_user
    user = await self.db.async_run_sync(self._create_role_user_sync, role_key)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy_database\database.py", line 194, in run_sync
    return await self.session.run_sync(fn, *args, **kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 189, in run_sync
    return await greenlet_spawn(fn, self.sync_session, *arg, **kw)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 128, in greenlet_spawn
    result = context.switch(value)
  File "C:\NoneBot2\.venv\lib\site-packages\fastapi_user_auth\auth\auth.py", line 204, in _create_role_user_sync
    role = session.scalar(select(Role).where(Role.key == role_key))
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 1742, in scalar
    return self.execute(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlmodel\orm\session.py", line 101, in execute
    return super().execute(  # type: ignore
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1564, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 531, in _compile_w_cache
    compiled_sql = self._compiler(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 566, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 790, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 463, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 498, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 3301, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\sql\base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 699, in create_for_statement
    _QueryEntity.to_compile_state(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 2451, in to_compile_state
    _MapperEntity(
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 2524, in __init__
    entity._post_inspect
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1184, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 2182, in _post_inspect
    self._check_configure()
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1924, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3483, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\NoneBot2\.venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3518, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped cl
ass MyUser->auth_user'. Original exception was: Multiple classes found for path "User" in the registry of this declarative base. Please use a fully module-quali
fied path.

02-14 09:23:15 [ERROR] uvicorn | Application startup failed. Exiting.
02-14 09:23:15 [ERROR] apscheduler | Error running job 207ed8e32a384304a515451c8ed806fb
Traceback (most recent call last):
  File "C:\NoneBot2\.venv\lib\site-packages\apscheduler\executors\base_py3.py", line 13, in run_coroutine_job
    async def run_coroutine_job(job, jobstore_alias, run_times, logger_name):
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\NoneBot2\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\NoneBot2\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\NoneBot2\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\NoneBot2\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\NoneBot2\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\NoneBot2\.venv\lib\site-packages\apscheduler\executors\asyncio.py", line 42, in callback
    events = f.result()
asyncio.exceptions.CancelledError

C:\NoneBot2>
```

**Comment by he0119** [comment]
请更新 datastore 到 0.5.8。

**Comment by yuanbuhuo** [comment]
嗯，可以了，十分感谢！
