### ISSUE TITLE
[bug]插件导入失败

### ISSUE THREAD

**Issue by sherlockHlb** [felinae98/nonebot-bison#225]
03-26 15:12:25 [ERROR] nonebot | Failed to import "nonebot_bison"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_bison\__init__.py", line 5, in <module>
    from . import (
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_bison\admin_page\__init__.py", line 17, in <module>
    from .api import router as api_router
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_bison\admin_page\api.py", line 8, in <module>
    from ..apis import check_sub_target
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_bison\apis.py", line 2, in <module>
    from .scheduler import scheduler_dict
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_bison\scheduler\__init__.py", line 1, in <module>
    from .manager import *
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_bison\scheduler\manager.py", line 3, in <module>
    from ..config import config
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_bison\config\__init__.py", line 1, in <module>
    from .db_config import config
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_bison\config\db_config.py", line 8, in <module>
    from sqlmodel import delete, func, select
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\sqlmodel\__init__.py", line 24, in <module>
    from sqlalchemy.schema import ThreadLocalMetaData as ThreadLocalMetaData
ImportError: cannot import name 'ThreadLocalMetaData' from 'sqlalchemy.schema' (C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\sqlalchemy\schema.py)
03-26 15:12:25 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_moyu"

根据报错信息可以看出，导入nonebot_bison插件失败了，原因是导入该插件时导入了sqlalchemy的ThreadLocalMetaData模块，但是该模块在sqlalchemy.schema中找不到。

可能的原因是sqlalchemy库版本太低或者安装不正确，或者nonebot_bison库中的代码有问题。

您可以尝试升级sqlalchemy库或重新安装nonebot_bison库。另外，您也可以在导入nonebot_bison之前先尝试单独导入sqlalchemy.schema，看看是否能正常导入。
但是并没有sqlalchemy库

**Comment by AzideCupric** [comment]
nonebot-bison版本？
nonebot-plugin-datastore版本？

**Comment by sherlockHlb** [comment]
nonebot-plugin-datastore in
c:\users\administrator\desktop\nbboot\fistbot\.venv\lib\site-packages
(0.6.0)
nonebot-bison in
c:\users\administrator\desktop\nbboot\fistbot\.venv\lib\site-packages
(0.7.0)

Luo Wei Zhi ***@***.***> 于2023年3月26日周日 16:25写道：

**Comment by AzideCupric** [comment]
考虑使用`pip install nonebot-bison==0.7.1 -i https://pypi.python.org/simple`来安装最新的版本
