### ISSUE TITLE
运行报错：No module named 'sqlmodel'

### ISSUE THREAD

**Issue by HuaOfSun** [felinae98/nonebot-bison#234]
## 环境

- nonebot-bison 版本：v0.7.1
- nonebot 版本：v2.0.0rc4
- 安装方式：（以下方式的一种或者其他方式）
  1. 通过 nb-cli 安装
- 操作系统：Windows Server 2022 Datacenter

## 问题
之前是用着无问题的，但我自己也忘了干了什么后bison在nb里加载不起来了(*/ω＼*)
安装后运行nb run加载插件后报错：ModuleNotFoundError: No module named 'sqlmodel'

## 日志

```
04-03 21:23:50 [ERROR] nonebot | Failed to import "nonebot_bison"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nb\nbbot2\bot.py", line 17, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_bison\__init__.py", line 5, in <module>
    from . import (
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_bison\admin_page\__init__.py", line 17, in <module>
    from .api import router as api_router
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_bison\admin_page\api.py", line 8, in <module>
    from ..apis import check_sub_target
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_bison\apis.py", line 2, in <module>
    from .scheduler import scheduler_dict
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_bison\scheduler\__init__.py", line 1, in <module>
    from .manager import *
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_bison\scheduler\manager.py", line 3, in <module>
    from ..config import config
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_bison\config\__init__.py", line 1, in <module>
    from .db_config import config
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_bison\config\db_config.py", line 8, in <module>
    from sqlmodel import delete, func, select
ModuleNotFoundError: No module named 'sqlmodel'
```
![0ONS)B36X3`22Y7 KWVSB4G](https://user-images.githubusercontent.com/125564413/229522964-8c988e52-4946-4fa6-b462-f8f993a66a0e.png)

- [ ] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [ ] 我确认在日志中去掉了敏感信息

**Comment by felinae98** [comment]
用 pypi mirror 了吗

**Comment by he0119** [comment]
这 bison 版本肯定不对啊，0.7.1 怎么可能有 sqlmodel（

**Comment by HuaOfSun** [comment]
> 这 bison 版本肯定不对啊，0.7.1 怎么可能有 sqlmodel（

对的，写错了，是0.7.0的版本

**Comment by HuaOfSun** [comment]
> 用 pypi mirror 了吗
是镜像源下载嘛，我把清华源设为默认下载了_(:з)∠)_

**Comment by he0119** [comment]
> > 这 bison 版本肯定不对啊，0.7.1 怎么可能有 sqlmodel（
> 
> 对的，写错了，是0.7.0的版本

升级 bison 或者降级 datastore 的版本都可以解决报错的问题。

**Comment by HuaOfSun** [comment]
> > > 这 bison 版本肯定不对啊，0.7.1 怎么可能有 sqlmodel（
> > 
> > 
> > 对的，写错了，是0.7.0的版本
> 
> 升级 bison 或者降级 datastore 的版本都可以解决报错的问题。

இ௰இ大佬，刚刚试了下把bison升级到0.7.1，降级0.6.3、0.6.2等，然后datastore升级0.6.2，也降级过0.6.1、0.6.0、0.5.10等，Nonebot test frontend will be running at: http://localhost:8080/bison这个出来了，但是后面继续加载的时候报了其他错误233


日志如下：
04-04 00:40:15 [INFO] nonebot_bison | Nonebot test frontend will be running at: http://localhost:8080/bison
04-04 00:40:15 [SUCCESS] nonebot | Succeeded to import "nonebot_bison"
04-04 00:40:15 [SUCCESS] nonebot | Running NoneBot...
04-04 00:40:16 [INFO] logging | Started server process [4508]
04-04 00:40:16 [INFO] logging | Waiting for application startup.
04-04 00:40:16 [INFO] nonebot_plugin_apscheduler | Scheduler Started
04-04 00:40:16 [ERROR] logging | Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 254, in _handle_exception
    raise error
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: there is already another table or index with this name: nonebot_bison_target

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_plugin_datastore\db.py", line 87, in init_db
    await run_upgrade()
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_plugin_datastore\script\utils.py", line 120, in run_upgrade
    await upgrade(config, "head")
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_plugin_datastore\script\command.py", line 245, in upgrade
    await run_migration()
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_plugin_datastore\script\utils.py", line 108, in run_migration
    await connection.run_sync(do_run_migrations, plugin_name)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 787, in run_sync
    return await greenlet_spawn(fn, self._proxied, *arg, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 167, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_plugin_datastore\script\utils.py", line 100, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\alembic\runtime\environment.py", line 867, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\alembic\runtime\migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\nonebot_bison\config\migrations\5da28f6facb3_rename_tables.py", line 20, in upgrade
    op.rename_table("target", "nonebot_bison_target")
  File "<string>", line 8, in rename_table
  File "<string>", line 3, in rename_table
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\alembic\operations\ops.py", line 1397, in rename_table
    return operations.invoke(op)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\alembic\operations\base.py", line 401, in invoke
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\alembic\operations\toimpl.py", line 122, in rename_table
    operations.impl.rename_table(
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\alembic\ddl\impl.py", line 346, in rename_table    self._exec(
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\alembic\ddl\impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\sql\ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1526, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 254, in _handle_exception
    raise error
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\nb\nbbot2\.venv\Lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
             ^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) there is already another table or index with this name: nonebot_bison_target
[SQL: ALTER TABLE target RENAME TO nonebot_bison_target]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

04-04 00:40:16 [ERROR] logging | Application startup failed. Exiting.



![1233](https://user-images.githubusercontent.com/125564413/229576019-87b08a5c-7357-4748-a06c-a494e9a4e76a.png)

**Comment by felinae98** [comment]
报这个错的时候使用的是什么版本

**Comment by HuaOfSun** [comment]
> 报这个错的时候使用的是什么版本
感谢大佬抽空解答，我折腾了一下在自己本地的主机上成功了，可以正常使用了_(:з)∠)_
