### ISSUE TITLE
在Debian下使用nbcli安装bison后报错

### ISSUE THREAD

**Issue by wisme2** [felinae98/nonebot-bison#260]
## 环境

- nonebot-bison 版本：0.7.2
- nonebot 版本：2.0.0rc4
- 安装方式：通过 nb-cli 安装
- 操作系统：Debian11(bullseye)  OpenStick

## 问题

无法加载nonebot_bison

## 日志

05-21 14:02:43 [ERROR] nonebot | Failed to import "nonebot_plugin_datastore"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot_bison/__init__.py", line 4, in <module>    require("nonebot_plugin_datastore")
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 168, in require
    plugin = load_plugin(name)
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_datastore/__init__.py", line 5, in <module>
    from .db import create_session as create_session
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_datastore/db.py", line 116, in <module>
    _engine = _make_engine()
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_datastore/db.py", line 44, in _make_engine
    return create_async_engine(url, **engine_options)
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 85, in create_async_engine
    sync_engine = _create_engine(url, **kw)
  File "<string>", line 2, in create_engine
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 283, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 337, in import_dbapi
    __import__("aiosqlite"), __import__("sqlite3")
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/aiosqlite/__init__.py", line 6, in <module>
    from sqlite3 import (  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

05-21 14:02:43 [ERROR] nonebot | Failed to import "nonebot_bison"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot_bison/__init__.py", line 4, in <module>    require("nonebot_plugin_datastore")
  File "/home/user/Python-3.11.3/nbot/.venv/lib/python3.11/site-packages/nonebot/plugin/load.py", line 170, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_datastore"!

日志显示找不到模块sqlite3，且无法加载nonebot_plugin_datastore
尝试直接安装后无果
nonebot_plugin_datastore版本为0.6.3

**Comment by felinae98** [comment]
这个 python3.11 是怎么装的呢，自己编译安装的吗

**Comment by wisme2** [comment]
是的

**Comment by felinae98** [comment]
大概是编译的时候没有enable python的sqlite feature，建议尝试重新编译python

**Comment by wisme2** [comment]
解决了，的确是编译时没把sqlite的选项写进去
感谢大佬指教！
