### ISSUE TITLE
未能成功推送GitHub官方的相关RSS源，原因不详

### ISSUE THREAD

**Issue by zzz6839** [felinae98/nonebot-bison#275]
## 环境

- nonebot-bison 版本：felinae98/nonebot-bison:latest
- nonebot 版本：不清楚
- 安装方式：docker compose
- 操作系统：win11 docker for win

## 问题

我有两个未能成功的GitHub官方的相关RSS源，不知道什么情况，麻烦大佬看一下，谢谢啦
https://github.com/R3nzTheCodeGOD/R3nzSkin/releases.atom
https://github.com/real-web-world/hh-lol-prophet/releases.atom

## 日志

```
2023-06-25 09:29:27 bison-nonebot-1    | 06-25 09:29:27 [WARNING] nonebot_bison | API request record: https://github.com/R3nzTheCodeGOD/R3nzSkin/releases.atom Headers({'host': 'github.com', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'cookie': '_octo=GH1.1.233686715.1687502668; logged_in=no; _gh_sess=bk1sS4sJuoNVMZqY%2F9u4dGxBg8C77Q%2B%2BAdAo3XyqWf23uhtvtprSpHA9U0BRLbnIcQd2eXusS2%2FBIr12dmtvw45bL%2FPWZ3otwGGQp%2BTw%2BKlHKHXa85txMwdRy%2FhuERdEZkXuNKn%2FQkgN57hTO2%2FZ2SbNtmglBReEg%2BoFLJubUe9HL3l7E9J7nlDE6Wc1DZKDskOd2qtQyGQfao6h1DWUJg%2F8%2FMA%2BtMflri3KtFcIqZ8gY5GZFWx8ylt8W%2B1kLMAkVJAzbp2IRjS0T0R1uo%2B8mw%3D%3D--04NIEW5X97zBC5Ud--b35dPPJoL%2F2MqQyR2QlyYw%3D%3D'}) | [200] Headers({'server': 'GitHub.com', 'date': 'Sun, 25 Jun 2023 01:29:26 GMT', 'content-type': 'application/atom+xml; charset=utf-8', 'vary': 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With', 'etag': 'W/"c3aae5581832f1bbca3d4bc8e67994b5"', 'cache-control': 'max-age=0, private, must-revalidate', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-frame-options': 'deny', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'referrer-policy': 'no-referrer-when-downgrade', 'content-security-policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com objects-origin.githubusercontent.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events *.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ wss://*.actions.githubusercontent.com github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com objects-origin.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/", 'accept-ranges': 'bytes', 'content-length': '6180', 'x-github-request-id': '7292:4F9E:C69A5A:D7A2DD:64979876'}) b64encoded: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPGZlZWQgeG1sbnM=
2023-06-25 09:29:27 bison-nonebot-1    | 06-25 09:29:27 [ERROR] apscheduler | Job "Scheduler.exec_fetch (trigger: interval[0:00:30], next run at: 2023-06-25 09:29:56 CST)" raised an exception
2023-06-25 09:29:27 bison-nonebot-1    | Traceback (most recent call last):
2023-06-25 09:29:27 bison-nonebot-1    |   File "/usr/local/lib/python3.10/site-packages/feedparser/util.py", line 156, in __getattr__
2023-06-25 09:29:27 bison-nonebot-1    |     return self.__getitem__(key)
2023-06-25 09:29:27 bison-nonebot-1    |   File "/usr/local/lib/python3.10/site-packages/feedparser/util.py", line 113, in __getitem__
2023-06-25 09:29:27 bison-nonebot-1    |     return dict.__getitem__(self, key)
2023-06-25 09:29:27 bison-nonebot-1    | KeyError: 'published_parsed'
2023-06-25 09:29:27 bison-nonebot-1    | 
2023-06-25 09:29:27 bison-nonebot-1    | During handling of the above exception, another exception occurred:
2023-06-25 09:29:27 bison-nonebot-1    | 
2023-06-25 09:29:27 bison-nonebot-1    | Traceback (most recent call last):
2023-06-25 09:29:27 bison-nonebot-1    |   File "/app/bot.py", line 18, in <module>
2023-06-25 09:29:27 bison-nonebot-1    |     nonebot.run()
2023-06-25 09:29:27 bison-nonebot-1    |   File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
2023-06-25 09:29:27 bison-nonebot-1    |     get_driver().run(*args, **kwargs)
2023-06-25 09:29:27 bison-nonebot-1    |   File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
2023-06-25 09:29:27 bison-nonebot-1    |     uvicorn.run(
2023-06-25 09:29:27 bison-nonebot-1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 568, in run
2023-06-25 09:29:27 bison-nonebot-1    |     server.run()
2023-06-25 09:29:27 bison-nonebot-1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
2023-06-25 09:29:27 bison-nonebot-1    |     return asyncio.run(self.serve(sockets=sockets))
2023-06-25 09:29:27 bison-nonebot-1    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2023-06-25 09:29:27 bison-nonebot-1    |     return loop.run_until_complete(main)
2023-06-25 09:29:27 bison-nonebot-1    | > File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
2023-06-25 09:29:27 bison-nonebot-1    |     retval = await job.func(*job.args, **job.kwargs)
2023-06-25 09:29:27 bison-nonebot-1    |   File "/app/nonebot_bison/scheduler/scheduler.py", line 96, in exec_fetch
2023-06-25 09:29:27 bison-nonebot-1    |     to_send = await platform_obj.do_fetch_new_post(
2023-06-25 09:29:27 bison-nonebot-1    |   File "/app/nonebot_bison/platform/platform.py", line 94, in do_fetch_new_post
2023-06-25 09:29:27 bison-nonebot-1    |     return await self.fetch_new_post(target, users)
2023-06-25 09:29:27 bison-nonebot-1    |   File "/app/nonebot_bison/platform/platform.py", line 319, in fetch_new_post
2023-06-25 09:29:27 bison-nonebot-1    |     new_posts = await self.filter_common_with_diff(target, post_list)
2023-06-25 09:29:27 bison-nonebot-1    |   File "/app/nonebot_bison/platform/platform.py", line 291, in filter_common_with_diff
2023-06-25 09:29:27 bison-nonebot-1    |     filtered_post = await self.filter_common(raw_post_list)
2023-06-25 09:29:27 bison-nonebot-1    |   File "/app/nonebot_bison/platform/platform.py", line 258, in filter_common
2023-06-25 09:29:27 bison-nonebot-1    |     (post_time := self.get_date(raw_post))
2023-06-25 09:29:27 bison-nonebot-1    |   File "/app/nonebot_bison/platform/rss.py", line 34, in get_date
2023-06-25 09:29:27 bison-nonebot-1    |     return calendar.timegm(post.published_parsed)
2023-06-25 09:29:27 bison-nonebot-1    |   File "/usr/local/lib/python3.10/site-packages/feedparser/util.py", line 158, in __getattr__
2023-06-25 09:29:27 bison-nonebot-1    |     raise AttributeError("object has no attribute '%s'" % key)
2023-06-25 09:29:27 bison-nonebot-1    | AttributeError: ("object has no attribute 'published_parsed'", ['https://github.com/R3nzTheCodeGOD/R3nzSkin/releases.atom Headers({\'host\': \'github.com\', \'accept\': \'*/*\', \'accept-encoding\': \'gzip, deflate\', \'connection\': \'keep-alive\', \'user-agent\': \'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36\', \'cookie\': \'_octo=GH1.1.233686715.1687502668; logged_in=no; _gh_sess=bk1sS4sJuoNVMZqY%2F9u4dGxBg8C77Q%2B%2BAdAo3XyqWf23uhtvtprSpHA9U0BRLbnIcQd2eXusS2%2FBIr12dmtvw45bL%2FPWZ3otwGGQp%2BTw%2BKlHKHXa85txMwdRy%2FhuERdEZkXuNKn%2FQkgN57hTO2%2FZ2SbNtmglBReEg%2BoFLJubUe9HL3l7E9J7nlDE6Wc1DZKDskOd2qtQyGQfao6h1DWUJg%2F8%2FMA%2BtMflri3KtFcIqZ8gY5GZFWx8ylt8W%2B1kLMAkVJAzbp2IRjS0T0R1uo%2B8mw%3D%3D--04NIEW5X97zBC5Ud--b35dPPJoL%2F2MqQyR2QlyYw%3D%3D\'}) | [200] Headers({\'server\': \'GitHub.com\', \'date\': \'Sun, 25 Jun 2023 01:29:26 GMT\', \'content-type\': \'application/atom+xml; charset=utf-8\', \'vary\': \'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With\', \'etag\': \'W/"c3aae5581832f1bbca3d4bc8e67994b5"\', \'cache-control\': \'max-age=0, private, must-revalidate\', \'strict-transport-security\': \'max-age=31536000; includeSubdomains; preload\', \'x-frame-options\': \'deny\', \'x-content-type-options\': \'nosniff\', \'x-xss-protection\': \'0\', \'referrer-policy\': \'no-referrer-when-downgrade\', \'content-security-policy\': "default-src \'none\'; base-uri \'self\'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src \'self\' uploads.github.com objects-origin.githubusercontent.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events *.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ wss://*.actions.githubusercontent.com github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action \'self\' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors \'none\'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src \'self\' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com objects-origin.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com *.githubusercontent.com; manifest-src \'self\'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com; script-src github.githubassets.com; style-src \'unsafe-inline\' github.githubassets.com; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/", \'accept-ranges\': \'bytes\', \'content-length\': \'6180\', \'x-github-request-id\': \'7292:4F9E:C69A5A:D7A2DD:64979876\'}) b64encoded: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPGZlZWQgeG1sbnM='])
```

- [ ✔] 我搜索过了 issue，但是并没有发现过与我类似的问题
- [✔ ] 我确认在日志中去掉了敏感信息

**Comment by UKMeng** [comment]
原因：不同RSS源时间标签使用可能会出现不规范的情况，代码没考虑到，比如https://github.com/R3nzTheCodeGOD/R3nzSkin/releases.atom使用的是<updated>而没有<published>
另外注意到https://rsshub.app/wallhaven/hot?limit=5甚至没有时间标签
有空的时候修
