### ISSUE TITLE
安装后运行报错

### ISSUE THREAD

**Issue by OVER4041** [felinae98/nonebot-bison#93]
开发大大好，我这边安装完运行报错，麻烦大大看一下哪里出问题了，谢谢
C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "07-19 12:24:51 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
07-19 12:24:51 [ERROR] nonebot | Failed to import "nonebot_plugin_htmlrender"
Traceback (most recent call last):
  File "e:\pbot\nb1\bot.py", line 31, in <module>
    nonebot.load_plugin("nonebot_bison")
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\__init__.py", line 1, in <module>
    from . import (
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\admin_page\__init__.py", line 17, in <module>
    from .api import (
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\admin_page\api.py", line 4, in <module>
    from ..config import Config, NoSuchSubscribeException, NoSuchUserException
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\config.py", line 10, in <module>
    from .platform import platform_manager
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\platform\__init__.py", line 6, in <module>
    from .platform import NoTargetGroup, Platform
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\platform\platform.py", line 13, in <module>
    from ..post import Post
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\post.py", line 11, in <module>
    from .utils import http_client, parse_text
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\utils\__init__.py", line 38, in <module>
    require("nonebot_plugin_htmlrender")
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 163, in require
    plugin = load_plugin(name)
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 159, in load_plugin
    raise RuntimeError(
RuntimeError: Module nonebot_plugin_htmlrender is not loaded as a plugin! Make sure not to import it before loading.
07-19 12:24:51 [ERROR] nonebot | Failed to import "nonebot_bison"
Traceback (most recent call last):
  File "e:\pbot\nb1\bot.py", line 31, in <module>
    nonebot.load_plugin("nonebot_bison")
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\__init__.py", line 1, in <module>
    from . import (
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\admin_page\__init__.py", line 17, in <module>
    from .api import (
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\admin_page\api.py", line 4, in <module>
    from ..config import Config, NoSuchSubscribeException, NoSuchUserException
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\config.py", line 10, in <module>
    from .platform import platform_manager
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\platform\__init__.py", line 6, in <module>
    from .platform import NoTargetGroup, Platform
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\platform\platform.py", line 13, in <module>
    from ..post import Post
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\post.py", line 11, in <module>
    from .utils import http_client, parse_text
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_bison\utils\__init__.py", line 38, in <module>
    require("nonebot_plugin_htmlrender")
  File "C:\Users\OVER404\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 165, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_htmlrender"!

**Comment by felinae98** [comment]
请详细描述一下你的 安装 和 运行 方式？

**Comment by OVER4041** [comment]
> 请详细描述一下你的 安装 和 运行 方式？

你好！谢谢你的回复，我使用的nb安装，第一次直接nb run运行失败报错后我卸载了于是使用 pip 安装后用bot载入插件还是报错这个。麻烦了

**Comment by felinae98** [comment]
这边不太好复现，可以尝试一下使用poetry和系统的环境做一个隔离

**Comment by felinae98** [comment]
太久没有回复，关闭这个 issue
